BCRUPro/BCRUPro/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib import admin
from django.urls import path, re_path, include
from BCRUPro.views import *
from rest_framework import routers
from login.views import login
from rest.views import *

app_name = 'BCRUPro'

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login),
    path('login/', include('login.urls', namespace="login")),
    path('', include(router.urls)),
    path('api/', include('rest.urls', namespace="rest")),
    path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    re_path(r'^index', index, name='index'),
    re_path(r'^index2', index2, name='index2'),
    re_path(r'^index3', index3, name='index3'),
    re_path(r'^nodeDetail', node_detail, name='node_detail'),
    re_path(r'^create_new_node', create_new_node, name='create_new_node'),
    re_path(r'^nodeEdit', node_edit, name='node_edit'),

    re_path(r'^user_manage', user_manage, name='user_manage'),
    re_path(r'^block_display', block_display, name='block_display'),
    re_path(r'^block_details', block_details, name='block_details'),
    re_path(r'^block_delete', block_delete, name='block_delete'),
    re_path(r'^create_new_block', create_new_block, name='create_new_block'),

    re_path(r'^invite_bids_display', invite_bids_display, name='invite_bids_display'),
    re_path(r'^create_invite_bids', create_invite_bids, name='create_invite_bids'),
    re_path(r'^offer_bids', offer_bids, name='offer_bids'),
    re_path(r'^check_offers', check_offers, name='check_offers'),
    re_path(r'^sign_bids', sign_bids, name='sign_bids'),
    re_path(r'^deploy_bids', deploy_bids, name='deploy_bids'),

    re_path(r'^mall', mall, name='mall'),
    re_path(r'^sign_order', sign_order, name='sign_order'),
    re_path(r'^vendor_display', vendor_display, name='vendor_display'),
    re_path(r'^order_delete', order_delete, name='order_delete'),
    re_path(r'^buy', buy, name='buy'),
    re_path(r'^order_display', order_display, name='order_display'),
    re_path(r'^order_detail', order_detail, name='order_detail'),

    re_path(r'^agriculture', agriculture, name='agriculture'),
    re_path(r'^product_detail', product_detail, name='product_detail'),

    re_path(r'^get_crops_data', get_crops_data, name='get_crops_data'),
    re_path(r'^update_crops_data', update_crops_data, name='get_crops_data'),
    re_path(r'^crops_deploy', crops_deploy, name='crops_deploy'),
    re_path(r'^get_deploy_status', get_deploy_status, name='get_deploy_status'),
    re_path(r'^search_deploy_crop', search_deploy_crop, name='search_deploy_crop'),
    re_path(r'^update_deploy_status', update_deploy_status, name='update_deploy_status'),
]

BCRUPro/login/urls.py
from django.conf.urls import url
from django.contrib import admin
from login import views

app_name = 'login'

urlpatterns = [
    url(r'^login/', views.login, name="login"),
    url(r'^register/', views.register, name="register"),
    url(r'^forgot_password/', views.forgot_password, name="forgot_password"),
    url(r'^logout/', views.logout, name="logout"),
]

BCRUPro/rest/urls.py
from django.urls import include, path
from django.conf.urls import url
from . import views
app_name = 'rest'

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^orders/$', views.orders_list, name='order_list'),
]

BCRUPro/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.highcharts.com.cn/jquery/jquery-1.8.3.min.js"></script>
  <script src="https://cdn.highcharts.com.cn/highstock/highstock.js"></script>
  <script src="https://cdn.highcharts.com.cn/highcharts/modules/exporting.js"></script>
  <script src="https://code.highcharts.com.cn/highcharts-plugins/highcharts-zh_CN.js"></script>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/summernote/summernote-bs4.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  {% block head %}

  {% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'index' %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'user_manage' %}" class="nav-link">UserManage</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static 'adminlte/dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static 'adminlte/dist/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static 'adminlte/dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'login:logout' %}" class="nav-link">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index.html" class="brand-link">
      <img src="{% static 'adminlte/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">BMS</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'adminlte/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ owner.name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-book"></i>
              <p>
                Products
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'agriculture' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Agriculture</p>
                </a>
              </li>
            </ul>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Games</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
{#        <div class="row mb-2">#}
{#          <div class="col-sm-6">#}
{#            <h1 class="m-0 text-dark">Dashboard</h1>#}
{#          </div><!-- /.col -->#}
{#          <div class="col-sm-6">#}
{#            <ol class="breadcrumb float-sm-right">#}
{#              <li class="breadcrumb-item"><a href="#">Home</a></li>#}
{#              <li class="breadcrumb-item active">Dashboard v1</li>#}
{#            </ol>#}
{#          </div><!-- /.col -->#}
{#        </div><!-- /.row -->#}
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->

    <section class="content">
        {% block content %}

        {% endblock %}

    </section>

    <!-- /.content -->
  </div>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'adminlte/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'adminlte/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'adminlte/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/jqvmap/maps/jquery.vmap.cn.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'adminlte/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'adminlte/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'adminlte/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'adminlte/dist/js/demo.js' %}"></script>
{% block script %}

{% endblock %}

</body>
</html>

BCRUPro/templates/baseLogin.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    {% block head %}

    {% endblock %}
</head>
<body class="hold-transition login-page">
    {% block content %}

    {% endblock %}

<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
{% block script %}

{% endblock %}
</body>
</html>

BCRUPro/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}



{% block head %}
    <title>AdminLTE 3 | Dashboard</title>
{% endblock %}



    <!-- Main content -->
{% block content %}

<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        {% for nodeWithColor in nodesWithColors %}
        <div class="col-lg-3 col-6">
        <!-- small box -->
            <div class="small-box {{ nodeWithColor.color }}">
              <div class="inner">
                <h3>NID: {{ nodeWithColor.node.device_id }}</h3>
                <p>Today Revenue:{{ nodeWithColor.node.today_revenue}}</p>
                <p>Summary: {{ nodeWithColor.node.summary_revenue}}</p>
                <p>Location: {{ nodeWithColor.node.location}}</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        {% endfor %}
    </div>
        <!-- Main row -->
    <div class="row">
      <!-- Left col -->
      <section class="col-lg-6 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
          <div class="card">
              <div class="card-header">
                <h3 class="card-title">
                  <i class="fas fa-chart-line mr-1"></i>
                  Sales
                </h3>
                <div class="card-tools">
                  <ul class="nav nav-pills ml-auto">
                    <li class="nav-item">
                      <a class="nav-link active" href="#revenue-chart" data-toggle="tab">Area</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#sales-chart" data-toggle="tab">Donut</a>
                    </li>
                  </ul>
                </div>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content p-0">
                  <div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 400px">
                      <div id="revenue_plot" height="400" style="height: 400px;"></div>
                  </div>
                  <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 400px;">
                      <div id="node_pie" height="400" style="height: 400px;"></div>
                  </div>
                </div>
              </div><!-- /.card-body -->
            </div>

        <!-- /.card -->

      </section>
      <!-- /.Left col -->
      <!-- right col (We are only adding the ID to make the widgets sortable)-->
      <section class="col-lg-6 connectedSortable">
        <!-- Map card -->
        <div class="card bg-gradient-primary">
          <div class="card-header border-0">
            <h3 class="card-title">
              <i class="fas fa-map-marker-alt mr-1"></i>
              Visitors
            </h3>
            <!-- card tools -->
            <div class="card-tools">
              <button type="button"
                      class="btn btn-primary btn-sm daterange"
                      data-toggle="tooltip"
                      title="Date range">
                <i class="far fa-calendar-alt"></i>
              </button>
              <button type="button"
                      class="btn btn-primary btn-sm"
                      data-card-widget="collapse"
                      data-toggle="tooltip"
                      title="Collapse">
                <i class="fas fa-minus"></i>
              </button>
            </div>
            <!-- /.card-tools -->
          </div>
          <div class="card-body">
            <div id="world-map" style="height: 250px; width: 100%;"></div>
          </div>
          <!-- /.card-body-->
          <div class="card-footer bg-transparent">
            <div class="row">
              <div class="col-4 text-center">
                <div id="sparkline-1"></div>
                <div class="text-white">Visitors</div>
              </div>
              <!-- ./col -->
              <div class="col-4 text-center">
                <div id="sparkline-2"></div>
                <div class="text-white">Online</div>
              </div>
              <!-- ./col -->
              <div class="col-4 text-center">
                <div id="sparkline-3"></div>
                <div class="text-white">Sales</div>
              </div>
              <!-- ./col -->
            </div>
            <!-- /.row -->
          </div>
        </div>
        <!-- /.card -->
      </section>
      <!-- right col -->
    </div>

</div><!-- /.container-fluid -->

    <!-- /.content -->
{% endblock %}

{% block script %}
    <script src="{% static 'adminlte/dist/js/pages/dashboard.js' %}"></script>
    <script src="{% static 'js/highcharts.js' %}"></script>

<script language="JavaScript">
$(document).ready(function() {
   var chart = {
      type: 'areaspline'
   };
   var title = {
      text: 'Revenue'
   };
   var subtitle = {
      style: {
         position: 'absolute',
         right: '0px',
         bottom: '10px'
      }
   };
   var legend = {
      layout: 'vertical',
      align: 'left',
      verticalAlign: 'top',
      x: 60,
      y: 20,
      floating: true,
      borderWidth: 1,
      backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
   };
   var xAxis = {
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'
              ,'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
   };
   var yAxis = {
      title: {
         text: 'Value'
      }
   };
   var tooltip = {
       shared: true,
       valueSuffix: ' units'
   };
   var credits = {
       enabled: false
   };
   var plotOptions = {
      areaspline: {
         fillOpacity: 0.5
      }
   };
   var series= [
       {% for node, data in block_data.items %}
           {
               name: "{{ node }}",
               data: {{ data }}
           },
       {% endfor %}
   ];

   var json = {};
   json.chart = chart;
   json.title = title;
   json.subtitle = subtitle;
   json.xAxis = xAxis;
   json.yAxis = yAxis;
   json.legend = legend;
   json.plotOptions = plotOptions;
   json.credits = credits;
   json.series = series;
   $('#revenue_plot').highcharts(json);


   var chart1 = {
       plotBackgroundColor: null,
       plotBorderWidth: null,
       plotShadow: false
   };
   var title1 = {
      text: 'Revenue Pie'
   };
   var tooltip1 = {
      pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
   };
   var plotOptions1 = {
      pie: {
         allowPointSelect: true,
         cursor: 'pointer',
         dataLabels: {
            enabled: true,
            format: '<b>{point.name}%</b>: {point.percentage:.1f} %',
            style: {
               color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
            }
         }
      }
   };
   var series1= [{
      type: 'pie',
      name: 'Node pie',
      data: [
          {% for node, data in summary_data.items %}
              {% if node == "SH003" %}
                {
                    name: '{{node}}',
                    y: {{ data }},
                    sliced: true,
                    selected: true
                },
              {% else %}
                ["{{ node }}", {{ data }}],
              {% endif %}
          {% endfor %}
      ]
   }];
   // Radialize the colors
   Highcharts.getOptions().colors = Highcharts.map(Highcharts.getOptions().colors, function (color) {
      return {
         radialGradient: { cx: 0.5, cy: 0.3, r: 0.7 },
         stops: [
            [0, color],
            [1, Highcharts.Color(color).brighten(-0.3).get('rgb')] // darken
         ]
      };
   });

   var json1 = {};
   json1.chart = chart1;
   json1.title = title1;
   json1.tooltip = tooltip1;
   json1.series = series1;
   json1.plotOptions = plotOptions1;
   $('#node_pie').highcharts(json1);

});
</script>
{% endblock %}

BCRUPro/templates/order_display.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
  <title>users</title>
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    <!-- Main content -->
    <div class="container-fluid">
    <div class="row">
      <div class="col-12">

        <!-- /.card -->

        <div class="card">
              <div class="card-header">
                <h3 class="card-title">Orders</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="order_table" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      {% for th in theader %}
                        <th>
                            <strong>{{ th }}</strong>
                        </th>
                      {% endfor %}
                        <th>Option</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for order in orders %}
                    <tr>
                        <td>{{ order.order_id }}</td>
                        <td>{{ order.vendor.name }}</td>
                        <td>{{ order.user_number }}</td>
                        <td>{{ order.latency }}</td>
                        <td>{{ order.bandwidth_up }}</td>
                        <td>{{ order.capacity_up }}</td>
                        <td>{{ order.create_at }}</td>
                        <td>
                            <div>
                            <form method="post" action="{% url 'order_delete' %}">
                                <input type="hidden" name="order_id" value="{{ order.order_id }}">
                                <input type="submit" value="Delete" class="btn btn-sm btn-danger">
                            </form><br>
                            <form method="post" action="{% url 'order_detail' %}">
                                <input type="hidden" name="order_id" value="{{ order.order_id }}">
                                <input type="submit" value="Detail " class="btn btn-sm btn-info">
                            </form>
                            </div>
                        </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
    </div>
    {% if feedback_message %}
        <div class="alert alert-warning">
            <h>Feedback Message</h>
            <p>{{ feedback_message }}</p>
        </div>
    {% endif %}
    <!-- /.content -->
{% endblock %}


{% block script %}
    <!-- DataTables -->
    <script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script>
  $(function () {
    $('#order_table').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
{% endblock %}