BCRUPro/BCRUPro/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib import admin
from django.urls import path, re_path, include
from BCRUPro.views import *
from rest_framework import routers
from login.views import login
from rest.views import *

app_name = 'BCRUPro'

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login),
    path('login/', include('login.urls', namespace="login")),
    path('', include(router.urls)),
    path('api/', include('rest.urls', namespace="rest")),
    path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    re_path(r'^index', index, name='index'),
    re_path(r'^index2', index2, name='index2'),
    re_path(r'^index3', index3, name='index3'),
    re_path(r'^nodeDetail', node_detail, name='node_detail'),
    re_path(r'^create_new_node', create_new_node, name='create_new_node'),
    re_path(r'^nodeEdit', node_edit, name='node_edit'),

    re_path(r'^user_manage', user_manage, name='user_manage'),
    re_path(r'^block_display', block_display, name='block_display'),
    re_path(r'^block_details', block_details, name='block_details'),
    re_path(r'^block_delete', block_delete, name='block_delete'),
    re_path(r'^create_new_block', create_new_block, name='create_new_block'),

    re_path(r'^invite_bids_display', invite_bids_display, name='invite_bids_display'),
    re_path(r'^create_invite_bids', create_invite_bids, name='create_invite_bids'),
    re_path(r'^offer_bids', offer_bids, name='offer_bids'),
    re_path(r'^check_offers', check_offers, name='check_offers'),
    re_path(r'^sign_bids', sign_bids, name='sign_bids'),
    re_path(r'^deploy_bids', deploy_bids, name='deploy_bids'),

    re_path(r'^mall', mall, name='mall'),
    re_path(r'^sign_order', sign_order, name='sign_order'),
    re_path(r'^vendor_display', vendor_display, name='vendor_display'),
    re_path(r'^order_delete', order_delete, name='order_delete'),
    re_path(r'^buy', buy, name='buy'),
    re_path(r'^order_display', order_display, name='order_display'),
    re_path(r'^order_detail', order_detail, name='order_detail'),

    re_path(r'^agriculture', agriculture, name='agriculture'),
    re_path(r'^product_detail', product_detail, name='product_detail'),

    re_path(r'^get_crops_data', get_crops_data, name='get_crops_data'),
    re_path(r'^update_crops_data', update_crops_data, name='get_crops_data'),
    re_path(r'^crops_deploy', crops_deploy, name='crops_deploy'),
    re_path(r'^get_deploy_status', get_deploy_status, name='get_deploy_status'),
    re_path(r'^search_deploy_crop', search_deploy_crop, name='search_deploy_crop'),
    re_path(r'^update_deploy_status', update_deploy_status, name='update_deploy_status'),
]

BCRUPro/login/urls.py
from django.conf.urls import url
from django.contrib import admin
from login import views

app_name = 'login'

urlpatterns = [
    url(r'^login/', views.login, name="login"),
    url(r'^register/', views.register, name="register"),
    url(r'^forgot_password/', views.forgot_password, name="forgot_password"),
    url(r'^logout/', views.logout, name="logout"),
]

BCRUPro/rest/urls.py
from django.urls import include, path
from django.conf.urls import url
from . import views
app_name = 'rest'

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^orders/$', views.orders_list, name='order_list'),
]

BCRUPro/login/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    gender = (
        ('male', 'male'),
        ('female', 'female'),
    )
    
    role_choice = (
        ('customer', 'customer'),
        ('csp', 'csp'),
    )

    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    role = models.CharField(max_length=32, choices=role_choice, default='customer')
    sex = models.CharField(max_length=32, choices=gender, default='male')
    c_time = models.DateTimeField(auto_now_add=True)

    @staticmethod
    def get_threader():
        return ["Name", "Email"]

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['c_time']

BCRUPro/login/forms.py
from django import forms


class RegisterForm(forms.Form):
    gender = (
        ('male', "male"),
        ('female', "female"),
    )
    username = forms.CharField(label="Full name", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="Password", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_confirm = forms.CharField(label="Retype Password", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='Gender', choices=gender)

BCRUPro/login/views.py
import hashlib

from django.contrib.auth import authenticate
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.views.decorators.http import require_http_methods, require_GET

from BCRUPro.models import Product
from BCRUPro.views import get_nodes, get_revenue_data
from login.models import User


def hash_code(s, salt='mysite'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest()


@require_http_methods(['POST', 'GET'])
def login(request):
    # if request.session.get('is_login', None):
    #     context = get_nodes(request)
    #     context.update(get_revenue_data(request))
    #     return render(request, 'index.html', context=context)

    if request.method == 'GET':
        return render(request, 'pages/examples/login.html')
    else:
        email = request.POST.get('email')
        password = request.POST.get('password')
        try:
            user = User.objects.get(email=email)
        except Exception as e:
            print(e)
            user = None
        if user is not None:
            if user.password == hash_code(password):
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.name
                context = get_nodes(request)
                context.update(get_revenue_data(request))
                owner = User.objects.get(name=user.name)
                context.update({"owner": owner})

                product1 = Product.objects.all()[0:3]
                product2 = Product.objects.all()[3:]
                return render(request, 'pages/examples/agriculture.html', locals())
            else:
                return render(request, 'pages/examples/login.html', {"message": "Password is error"})
        else:
            return render(request, 'pages/examples/login.html', {"message": "Account is not exist"})


@require_http_methods(['POST', 'GET'])
def register(request):
    if request.method == 'GET':
        return render(request, 'pages/examples/register.html')
    else:
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        role = request.POST.get('role')
        password_confirm = request.POST.get('password_confirm')
        if password != password_confirm:
            return render(request, 'pages/examples/register.html', {"message": "The two passwords do not match"})
        else:
            same_name_user = User.objects.filter(name=name)
            if same_name_user:
                return render(request, 'pages/examples/register.html', {"message": "The user name is exist"})
            same_email_user = User.objects.filter(email=email)
            if same_email_user:
                return render(request, 'pages/examples/register.html', {"message": "The email is registered"})

            new_user = User.objects.create()
            new_user.name = name
            new_user.email = email
            new_user.password = hash_code(password)
            new_user.role = role
            new_user.save()
            return render(request, 'pages/examples/login.html')


@require_GET
def forgot_password(request):
    return render(request, 'pages/examples/forgot-password.html')


@require_GET
def logout(request):
    request.session.flush()
    return render(request, 'pages/examples/login.html')

BCRUPro/templates/pages/examples/agriculture.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <p>Products</p>
    <table class="table table-bordered" style="width:95%;height:auto;">
        <tr>
            {% for crop in crops1 %}
            <td width="200px" height="200px">
                <div>
                    <img src="{% static crop.image_name %}" alt="Product Image" style="width:400px;height:260px;">
                    <div><p>{{ crop.name }}</p></div>
                    <div>
                        <form method="get" action="{% url 'product_detail' %}">
                            <input type="hidden" name="product_name" value="{{ crop.name }}">
                            <input type="submit" value="Detail" class="btn btn-sm btn-info">
                        </form>
                    </div>
                </div>
            </td>
            {% endfor %}
        </tr>
        <tr>
            {% for crop in crops2 %}
            <td width="200px" height="200px">
                <div>
                    <img src="{% static crop.image_name %}" alt="Product Image" style="width:400px;height:260px;">
                    <div><p>{{ crop.name }}</p></div>
                    <div>
                        <form method="get" action="{% url 'product_detail' %}">
                            <input type="hidden" name="product_name" value="{{ crop.name }}">
                            <input type="submit" value="Detail" class="btn btn-sm btn-info">
                        </form>
                    </div>
                </div>
            </td>
            {% endfor %}
        </tr>
    </table>

{% endblock %}

BCRUPro/templates/pages/examples/forgot-password.html
{% extends 'baseLogin.html' %}
{% load staticfiles %}

{% block content %}
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'index2' %}"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>

      <form action="recover-password.html" method="post">
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Request new password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="{% url 'login' %}">Login</a>
      </p>
      <p class="mb-0">
        <a href="{% url 'register' %}" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
{% endblock %}

BCRUPro/templates/pages/examples/invite-bids-deploy.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
  <title>users</title>
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    <div class="image">
          <img src="{% static 'adminlte/dist/img/TTM.gif' %}" class="product-image">
    </div>
{% endblock %}


{% block script %}
    <!-- DataTables -->
    <script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>

<!-- page script -->
{% endblock %}

BCRUPro/templates/pages/examples/invite-bids-display.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
  <title>users</title>
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    <!-- Main content -->
    <div class="container-fluid">
    <div class="row">
      <div class="col-12">

        <!-- /.card -->

        <div class="card">
              <div class="card-header">
                <h3 class="card-title">Invitation Bids</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      {% for th in theader %}
                        <th>
                            <strong>{{ th }}</strong>
                        </th>
                      {% endfor %}
                      {% if owner.role == "customer" %}
                          <th></th>
                      {% endif %}
                      {% if owner.role == "csp" %}
                          <th></th>
                      {% endif %}
                  </tr>
                  </thead>
                  <tbody>
                  {% for bid in invite_bids %}
                    <tr>
                        <td>{{ bid.invitation_id }}</td>
                        <td>{{ bid.node }}</td>
                        <td>{{ bid.network_type }}</td>
                        <td>{{ bid.area }}</td>
                        <td>{{ bid.time }}</td>
                        <td>{{ bid.number }}</td>
                        <td>{{ bid.data }}</td>
                        <td>{{ bid.create_at }}</td>
                        <td>{{ bid.winner }}</td>
                        {% if owner.role == "customer" %}
                            <td>
                                <form method="get" action="{% url 'check_offers' %}">
                                    <input type="hidden" name="invitation_id" value="{{ bid.invitation_id }}">
                                    <input type="submit" value="Check Offer" class="btn btn-sm btn-info">
                                </form>
                            </td>
{#                        <td>#}
{#                            <form method="post" action="{% url 'block_display' %}"> {# bids_delete #}
{#                                <input type="hidden" name="invitation_id" value="{{ bid.invitation_id }}">#}
{#                                <input type="submit" value="Close" class="btn btn-sm btn-danger">#}
{#                            </form>#}
{#                        </td>#}
                        {% endif %}
                        {% if owner.role == "csp" %}
                            {% if not bid.sign_status %}
                                 <td>
                                    <form method="get" action="{% url 'offer_bids' %}">
                                        <input type="hidden" name="invitation_id" value="{{ bid.invitation_id }}">
                                        <input type="submit" value="Offer Bids" class="btn btn-sm btn-info">
                                    </form>
                                 </td>
                            {% else %}
                                {% if owner.name == bid.winner %}
                                    <td>
                                        <form method="post" action="{% url 'deploy_bids' %}">
                                            <input type="hidden" name="invitation_id" value="{{ bid.invitation_id }}">
                                            <input type="submit" value="Deploy" class="btn btn-sm btn-info">
                                        </form>
                                    </td>
                                {% else %}
                                    <td>
                                        <button id="verify_bids" href="#" class="btn btn-sm btn-info">Verify</button>
                                    </td>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              {% if owner.role == "customer" %}
                <form method="get" action="{% url 'create_invite_bids' %}" style="float:left">
                        <input type="submit" value="Create Invitation Bid" class="btn btn-sm btn-info">
                </form>
              {% endif %}
              </div>
              <!-- /.card-body -->
            </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
    </div>
    {% if feedback_message %}
        <div class="alert alert-warning">
            <h>Feedback Message</h>
            <p>{{ feedback_message }}</p>
        </div>
    {% endif %}
    <!-- /.content -->
{% endblock %}


{% block script %}
    <!-- DataTables -->
    <script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>

<!-- page script -->

<script>
  $(function () {
    $("#example").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
    $('#example1').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });

  $('#deploy_bids').click(function(){
        $.ajax({
            type:'post',
            traditional :true,
            url:'{% url 'deploy_bids' %}',
            dataType: 'json',
            success:function(data){
                if(data.status == 'success'){
                    alert("Success");
                }else {
                    alert("Failed");
                }
            }
        });
        return false;
  });

    $('#verify_bids').click(function(){
        $.ajax({
            type:'get',
            traditional :true,
            url:'{% url 'deploy_bids' %}',
            dataType: 'json',
            success:function(data){
                if(data.status == 'success'){
                    alert("Success");
                }else {
                    alert("Failed");
                }
            }
        });
        return false;
  });
</script>
{% endblock %}

BCRUPro/templates/pages/examples/lockscreen.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Lockscreen</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition lockscreen">
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- User name -->
  <div class="lockscreen-name">John Doe</div>

  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
      <img src="../../dist/img/user1-128x128.jpg" alt="User Image">
    </div>
    <!-- /.lockscreen-image -->

    <!-- lockscreen credentials (contains the form) -->
    <form class="lockscreen-credentials">
      <div class="input-group">
        <input type="password" class="form-control" placeholder="password">

        <div class="input-group-append">
          <button type="button" class="btn"><i class="fas fa-arrow-right text-muted"></i></button>
        </div>
      </div>
    </form>
    <!-- /.lockscreen credentials -->

  </div>
  <!-- /.lockscreen-item -->
  <div class="help-block text-center">
    Enter your password to retrieve your session
  </div>
  <div class="text-center">
    <a href="login.html">Or sign in as a different user</a>
  </div>
  <div class="lockscreen-footer text-center">
    Copyright &copy; 2014-2019 <b><a href="http://adminlte.io" class="text-black">AdminLTE.io</a></b><br>
    All rights reserved
  </div>
</div>
<!-- /.center -->

<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>

BCRUPro/templates/pages/examples/login.html
{% extends 'baseLogin.html' %}
{% load staticfiles %}

{% block content %}


<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'index2' %}"><b>Admin</b>LTE</a>
  </div>
    {% if message %}
        <div class="alert alert-warning">{{ message }}</div>
    {% endif %}
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>
      <form action="{% url 'login:login' %}" method="post">
        <div class="input-group mb-3">
          <input name="email" type="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input name="password" type="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <div class="social-auth-links text-center mb-3">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
        </a>
      </div>
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="{% url 'login:forgot_password' %}">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="{% url 'login:register' %}" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
{% endblock %}

BCRUPro/templates/pages/examples/mall.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <p>Mall</p>
    <table class="table table-bordered" style="width:95%;height:auto;">
        <tr>
            {% for product in product1 %}
            <td width="200px" height="200px">
                <div>
                    <img src="{% static product.image_name %}" alt="Product Image" style="width:400px;height:260px;">
                    <p>Product Name: {{ product.name }}</p>
                    <div>
                        <form method="get" action="{% url 'vendor_display' %}">
                            <input type="hidden" name="product_name" value="{{ product.name }}">
                            <input type="submit" value="Buy" class="btn btn-sm btn-info">
                        </form>
                    </div>
                </div>
            </td>
            {% endfor %}
        </tr>
        <tr>
            {% for product in product2 %}
            <td width="200px" height="200px">
                <div>
                    <img src="{% static product.image_name %}" alt="Product Image" style="width:400px;height:260px;">
                    <p>Product Name: {{ product.name }}</p>
                    <div>
                        <form method="get" action="{% url 'vendor_display' %}">
                            <input type="hidden" name="product_name" value="{{ product.name }}">
                            <input type="submit" value="Buy" class="btn btn-sm btn-info">
                        </form>
                    </div>
                </div>
            </td>
            {% endfor %}
        </tr>
    </table>

{% endblock %}

BCRUPro/templates/pages/examples/node-add.html
{% extends 'base.html' %}
{% load staticfiles %}

    <!-- Main content -->
{% block content %}
    <form action="{% url 'create_new_node' %}" method="post">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">General</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <div class="card-body">
              <div class="form-group">
                <label for="inputName">Device ID</label>
                <input name="device_id" type="text" id="inputName" class="form-control">
              </div>
              <div class="form-group">
                <label for="inputName">Location</label>
                <input name="location" type="text" id="inputName" class="form-control">
              </div>
                <div class="row">
                <div class="col-md-6">
                  <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
                  <input type="submit" value="Create new node" class="btn btn-success float-right">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
{% endblock %}

BCRUPro/templates/pages/examples/register.html
{% extends 'baseLogin.html' %}
{% load staticfiles %}

{% block content %}
<div class="register-box">
  <div class="register-logo">
    <a href="{% url 'index2' %}"><b>Admin</b>LTE</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new membership</p>
    {% if message %}
        <div class="alert alert-warning">{{ message }}</div>
    {% endif %}

      <form action="{% url 'login:register' %}" method="post">
        <div class="input-group mb-3">
          <input name="name" type="text" class="form-control" placeholder="Full name">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input name="email" type="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
              <select name="role" type="text" class="form-control custom-select">
                  <option>customer</option>
                  <option>csp</option>
              </select>
        </div>
        <div class="input-group mb-3">
          <input name="password" type="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input name="password_confirm" type="password" class="form-control" placeholder="Retype password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="agreeTerms" name="terms" value="agree">
              <label for="agreeTerms">
               I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i>
          Sign up using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i>
          Sign up using Google+
        </a>
      </div>

      <a href="{% url 'login:login' %}" class="text-center">I already have a membership</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
{% endblock %}